language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - nightly

# command to install dependencies
install:
  - pip install emoji

# command to run tests
script: python tests/test.py
