language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - nightly

# command to install dependencies
install:
  - pip install emoji
  - pip install --quiet coveralls

# command to run tests
script:
  - python tests/test.py
  - coverage run --source=yatg tests/test.py

after_success:
  - coveralls
